{
	"ua": "",
	"homeUrl": "https://www.dqsj.cc/",
	"cateNode": "",
	"cateName": "",
	"cateId": "",
	"cateIdR": "",
	"cateManual": {
                   "热门新番": "23", 
                   "动漫大全": "20", "日本动漫": "21"  ,"国产动漫": "22"  ,"欧美动漫": "25" , 
                   "动漫电影": "24", 
                   "剧集": "27", 
                   "电影": "28", 
                   "综艺": "31"
                   },
	"homeVodNode": "//div[contains(@class,'module-item')]/div[contains(@class,'module-item-cover')]",
	"homeVodName": "/div/a/@title",
        "homeVodNameR": "",
	"homeVodId": "/div/a/@href",
	"homeVodIdR": "/index.php/vod/detail/id/(\\w+).html",
	"homeVodImg": "/div/img/@data-src",
        "homeVodImgR": "",
	"homeVodMark": "/div/span[2]/text()",
	"cateUrl": "https://www.dqsj.cc/index.php/vod/show/id/{cateId}/page/{catePg}.html",
	"cateVodNode": "//div[@class='module-item-cover']",
	"cateVodName": "/div/a/@title",
	"cateVodId": "/div/a/@href",
	"cateVodIdR": "/index.php/vod/detail/id/(\\w+).html",
	"cateVodImg": "/div/img/@data-src",
	"cateVodImgR": "",
	"cateVodMark": "/div/span[2]/text()",
	"dtUrl": "https://www.dqsj.cc/index.php/vod/detail/id/{vid}.html",
	"dtNode": "//body",
	"dtName": "//div[@class='video-info-header']/h1/text()",
	"dtNameR": "",
	"dtImg": "//div[@class='video-cover']/div/div/img/@data-src",
	"dtImgR": "",
	"dtDesc": "//div[@class='video-info-item video-info-content vod_content']/text()",
	"dtDescR": "",
	"dtFromNode": "//div[contains(@class,'module-tab-item tab-item')]",
	"dtFromName": "/@data-dropdown-value",
	"dtFromNameR": "",
	"dtUrlNode": "//div[@class='scroll-content']",
	"dtUrlSubNode": "/a",
	"dtUrlId": "@href",
	"dtUrlIdR": "/index.php/vod/play/id/(\\S+).html",
	"dtUrlName": "/span/text()",
	"dtUrlNameR": "",
	"playUrl": "https://www.dqsj.cc/index.php/vod/play/id/{playUrl}.html",
	"playUa": "",
	"searchUrl": "https://www.dqsj.cc/index.php/ajax/suggest?mid=1&wd={wd}&limit=10",
	"scVodNode": "json:list",
	"scVodName": "name",
	"scVodId": "id",
	"scVodIdR": "",
	"scVodImg": "pic",
	"scVodMark": ""
}